
    eureka:
        client:
            serviceUrl:
                defaultZone: http://localhost:10000/eureka/
    server:
        port: 10002
    spring:
        application:
            name: customer
        main:
            allow-bean-definition-overriding: true
        mvc:
          static-path-pattern: /**
        thymeleaf:
          servlet:
            content-type: text/html
          encoding: UTF-8
          cache: false
          mode: HTML5